### ISSUE TITLE
Error: Could not config mailbox store: unsupported inbox type

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#132]
**Describe the bug**
After running `./mailchain init`, I try to start the application with `./mailchain serve --log-level=debug`

I get an error:

```
2019/05/08 07:25:08 Could not config mailbox store: unsupported inbox type
```

It looks like the leveldb is not being created on `init`

**To Reproduce**
1. Run `./mailchain init`
2. Fill out the details
3. [Maybe not be needed] Add a key to the keystore (`./mailchain account add -K *********** -C ethereum`)
4. Run `./mailchain serve --log-level=debug`
5. See error

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.2`

**Expected behavior**
I expected the mailchain client to start without error

**Desktop (please complete the following information):**
 - OS: [iOS]
 
**Additional context**
**Config file:**

```
chains:
  ethereum:
    networks:
      ropsten:
        pubkey-finder: etherscan-no-auth
        receiver: etherscan-no-auth
        sender: ethereum-rpc2
clients:
  ethereum-rpc2:
    ropsten:
      address: https://ropsten.infura.io/v3/******************************
server:
  cors:
    allowed-origins: '*'
    disabled: false
  port: 8080
storage:
  keys: nacl-filestore
  mailbox: leveldb
  sent: s3
stores:
  leveldb:
    path: ./.mailchain/.mailbox
  nacl-filestore:
    path: ./.mailchain/.keystore
  s3:
    access-key-id: ******************************
    bucket: ******************************
    region: u******************************
    secret-access-key: ******************************

```

**Files in the folder:**

```
./mailchain
./LICENSE
./.mailchain
./.mailchain/.mailchain.yaml
./.mailchain/.keystore
./.mailchain/.keystore/******************************.json
```
