### ISSUE TITLE
Create default configuration for receiver

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#135]
**Is your feature request related to a problem? Please describe.**
.mailchain.yaml is a large file and some settings are defaults. 

**Describe the solution you'd like**
Remove the requirement to speficify default settings that bloat the configuration

**Describe alternatives you've considered**
N/A

**Additional context**
```
chains:
  ethereum:
    networks:
      mainnet:
        receiver: etherscan-no-auth
```
