### ISSUE TITLE
Error running 'mailchain serve' with partially configured protocols

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#303]
**Describe the bug**

**To Reproduce**
mailchain.yaml 
```
protocols:
  ethereum:
    disabled: false
    networks:
      goerli:
        disabled: false
        nameservice-address: ""
        nameservice-domain-name: ""
        public-key-finder: "etherscan-no-auth"
        receiver: ""
        sender: ""
```

`mailchain serve`
**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.1.0`

**Expected behavior**
No error but a partially configured endpoint
